### ISSUE TITLE
Misleading example, might lead to confusion.

### ISSUE THREAD

**Issue by idfunctor** [Runjuu/mst-effect#13]
The "handle-user-input" example has the following "gotchas"

1. The fetch function in utils does a Math.random() to create an error. This is not obvious to someone reading the code afresh, and causes confusion when they, for example, type their own Github account and it creates an error. One can easily get in the. "error" state by typing a  non-sensical word for the username, like "asjfkbaskjfbasg"

2. the promise-to-observable implementation in utils is confusing, and does *not* cause an error if the API results in an error.

Here is a fork of your example with a much more "idiomatic" Rx fetch that causes predictable errors.
https://codesandbox.io/s/handle-user-input-forked-gcge9?file=/src/app.tsx

Feel free to update your example if you deem this fit. 

Thanks a lot for this library, it is really cool and it is one of the major reasons why I switched from pure MobX to full-blown MST.

**Comment by Runjuu** [comment]
It looks great! 😁 I’ve updated the other examples as well.
