### ISSUE TITLE
Implicit error handling, can we make it optional?

### ISSUE THREAD

**Issue by idfunctor** [runjuu/mst-effect#22]
This library "eats up" all the errors of our stream and logs it out to the console.
https://github.com/Runjuu/mst-effect/blob/c96e9235cd8e10ded0d652bd924574d0c8354658/src/effect/utils.ts#L26

Can I try to make a pull request to make this optional somehow? Or are you against making that behaviour optional? I would prefer if the library didn't try to handle any error for me and let me deal with exceptions in my business logic, and cause panics on unhandled exceptions.

**Comment by Runjuu** [comment]
Yes! PRs are welcome 😁

Originally we use `logAngIgnoreError` is want to make sure error won't affect whole model.

**Comment by Runjuu** [comment]
BTW, If you want to deal with exceptions with your own business logic, you can always use catchError to accomplish that. Let me find an example for you.

**Comment by Runjuu** [comment]
https://codesandbox.io/s/fetch-data-i9hqb?file=/src/app.tsx:901-1051

How about this one? 🤔️
